-- 1. Справочник типов продукции (нужен для алгоритма расчета материалов - получения коэффициента)
CREATE TABLE IF NOT EXISTS product_types (
    product_type_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    type_name       VARCHAR(100) NOT NULL UNIQUE,
    coefficient     NUMERIC(10, 4) NOT NULL CHECK (coefficient > 0)
);

-- 2. Справочник типов материалов (нужен для алгоритма расчета материалов - получения процента брака)
CREATE TABLE IF NOT EXISTS material_types (
    material_type_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    material_name    VARCHAR(100) NOT NULL UNIQUE,
    waste_percent    NUMERIC(5, 2) NOT NULL CHECK (waste_percent >= 0.00 AND waste_percent <= 100.00)
);

-- 3. Таблица партнеров (информация о партнерах)
CREATE TABLE IF NOT EXISTS partners (
    partner_id     INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    legal_form     VARCHAR(50) NOT NULL,
    partner_name   VARCHAR(255) NOT NULL,
    inn            VARCHAR(12) NOT NULL UNIQUE,
    email          VARCHAR(255) NOT NULL UNIQUE,
    phone          VARCHAR(20) NOT NULL DEFAULT 'Not specified',
    address        TEXT NOT NULL DEFAULT 'Not specified',
    director_name  VARCHAR(255) NOT NULL DEFAULT 'Not specified',
    rating         NUMERIC(3, 2) NOT NULL DEFAULT 3.00 CHECK (rating >= 1.00 AND rating <= 5.00)
);

-- 4. Таблица продуктов (справочник номенклатуры)
CREATE TABLE IF NOT EXISTS products (
    product_id       INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_name     VARCHAR(255) NOT NULL,
    product_type_id  INT NOT NULL,
    material_type_id INT NOT NULL,
    stock            INT NOT NULL DEFAULT 0 CHECK (stock >= 0),
    price            DECIMAL(10, 2) NOT NULL CHECK (price >= 0),

    -- Ссылочная целостность для справочников
    CONSTRAINT fk_products_product_type
        FOREIGN KEY (product_type_id) REFERENCES product_types(product_type_id) ON DELETE RESTRICT,
    CONSTRAINT fk_products_material_type
        FOREIGN KEY (material_type_id) REFERENCES material_types(material_type_id) ON DELETE RESTRICT
);

-- 5. Таблица истории продаж (история реализации)
CREATE TABLE IF NOT EXISTS sales_history (
    sale_id       INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    partner_id    INT NOT NULL,
    product_id    INT NOT NULL,
    quantity      INT NOT NULL CHECK (quantity > 0),
    sale_price    DECIMAL(10, 2) NOT NULL CHECK (sale_price >= 0),
    total_amount  DECIMAL(12, 2) GENERATED ALWAYS AS (quantity * sale_price) STORED,
    sale_date     TIMESTAMP NOT NULL DEFAULT NOW(),

    -- Ссылочная целостность для партнеров и продуктов
    CONSTRAINT fk_sales_partner
        FOREIGN KEY (partner_id) REFERENCES partners(partner_id) ON DELETE RESTRICT,
    CONSTRAINT fk_sales_product
        FOREIGN KEY (product_id) REFERENCES products(product_id) ON DELETE RESTRICT
);

-- Индексы для обеспечения высокой производительности FOREIGN KEY
CREATE INDEX IF NOT EXISTS idx_products_product_type ON products(product_type_id);
CREATE INDEX IF NOT EXISTS idx_products_material_type ON products(material_type_id);
CREATE INDEX IF NOT EXISTS idx_sales_partner ON sales_history(partner_id);
CREATE INDEX IF NOT EXISTS idx_sales_product ON sales_history(product_id);
